### ISSUE TITLE
ethical hacking course is removed in youtube

### ISSUE THREAD

**Issue by Iam-Sherlock** [shreyaschavhan/oscp-pre-preparation-plan-and-notes#1]
The complete python ethical hacking course is removed in youtube 
Any other ways or any other links to watch that video

**Comment by shreyaschavhan** [comment]
Yeah! 

A quick tip:

- Use Wayback machine
- [Access it here](https://web.archive.org/web/20210222183051/https://www.youtube.com/watch?v=0NQ2aMxBYNE&feature=youtu.be)

**Comment by shreyaschavhan** [comment]
I'll update the repository with the link.

**Comment by Iam-Sherlock** [comment]
Thank you bro
